language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
    dist: xenial
    sudo: true
# The above 2 lines are a workaround to get python 3.7 support to work.
# Remove when Travis officially supports 3.7

git:
  depth: 3
install:
  - pip install --ignore-installed -e ./src
  - pip install --ignore-installed -r requirements.txt
before_script:
  - python scripts/check_and_use_custom_sdk.py
script:
  - scripts/verify.sh test
  - scripts/verify.sh lint
after_success:
  - coveralls
branches:
  only:
    - master


