language: python
python:
  - 2.7
  - 3.5
  - 3.6
git:
  depth: 3
install:
  - pip install -e ./src
  - pip install -r requirements.txt
script:
  - scripts/verify.sh test
  - scripts/verify.sh lint
after_success:
  - coveralls
branches:
  only:
    - master
